### ISSUE TITLE
感觉收集的项目很少，不够全面

### ISSUE THREAD

**Issue by zhouliuhuo** [CharleeWa/openai-toolbox#1]

**Comment by cwandev** [comment]
您好 @zhouliuhuo ！是的，这其实非常少。大概是因为两个原因，一是我目力所及范围是有限的，另外个人能力也是有限的，像是一些项目比较难搞懂，我就没有录入进来。今年作为AI元年，相信会有更多好用的工具出来，我会持续跟进。也希望大家一起参与进来，共同打造我们的工具流，谢谢关注！
