### ISSUE TITLE
More additions 

### ISSUE THREAD

**Issue by jackculpan** [CharleeWa/openai-toolbox#2]
Hey, thanks for adding my tool chatwebpage!

I'd love to put forward my other tools 60sec.site and webscrapeai.com

**Comment by cwandev** [comment]
Hi, @jackculpan. I'm delighted that you've shared your other tools with me. They're really fantastic, thank you so much!
Would you mind taking some time to create a pull request (PR) for me, using an English description?
Once again, thank you for your contribution, and have a great day!
